input LoginUserMutationInput {
  email: String!
  password: String!
}

type LoginUserResult {
  accessToken: String!
  user: User!
}

type Mutation {
  LoginUser(input: LoginUserMutationInput!): LoginUserResult
  RegisterUser(input: RegisterUserMutationInput!): User
  _m: String!
}

type Query {
  _q: String!
  me: User
}

input RegisterUserMutationInput {
  email: String!
  name: String!
  password: String!
  passwordConfirmation: String!
}

"""A user from the system"""
type User {
  active: Boolean!
  email: String!
  id: ID!
  name: String!
}
